version: "3.7"

networks:
  proxy-network:
    external: "true"


services:
    nextjs-dev:
      build: 
        context: .
        dockerfile: docker/dev/Dockerfile
      image: "portfolio-nextjs-dev:latest"
      container_name: "nextjs-dev"
      restart: "always"
      ports:
        - 3002:3000
      networks:
        - "proxy-network"
      environment:
        VIRTUAL_HOST: dev.shivamnaik.de
        LETSENCRYPT_HOST: dev.shivamnaik.de
        LETSENCRYPT_EMAIL: "ichbinshivamsnaik@outlook.com"
        VIRTUAL_PORT: 3000

