version: "3.7"

networks:
  proxy-network:
    external: "true"


services:
    nextjs:
      build: 
        context: .
      image: "portfolio-nextjs:latest"
      container_name: "nextjs"
      restart: "always"
      ports:
        - 3001:3000
      networks:
        - "proxy-network"
      environment:
        VIRTUAL_HOST: shivamnaik.de
        LETSENCRYPT_HOST: shivamnaik.de
        LETSENCRYPT_EMAIL: "ichbinshivamsnaik@outlook.com"
        VIRTUAL_PORT: 3000

